import {escapeHTML as e} from './utils.mjs';
import {casePage,detailList,processLine} from './case-layout.mjs';
import {renderExposureFomo,renderSelectedPnl} from './risk-figures.mjs';
const back='<a class="text-link" href="./index.html#work">← All Work</a>';
export function customerRiskPage(p,pagination,figures){
 const signals=p.signals.map((signal,i)=>`<li><span class="risk-index">0${i+1}</span><div><strong class="risk-signal-value">${e(signal.value)}</strong><h3>${e(signal.name)}</h3><p>${e(signal.description)}</p>${signal.note?`<p class="risk-note">${e(signal.note)}</p>`:''}</div></li>`).join('');
 const decisions=p.decisions.map(([title,description],i)=>`<li><span class="risk-index">0${i+1}</span><div><h3>${e(title)}</h3><p>${e(description)}</p></div></li>`).join('');
 const body=`<section id="overview" class="case-hero risk-hero container"><p class="eyebrow">RISK ANALYTICS / CUSTOMER ANALYTICS</p><h1 class="reveal ready">From transactions<br><span>to targeted risk review.</span></h1><noscript><style>.risk-hero h1.reveal.ready{opacity:1;transform:none}</style></noscript><p class="case-subtitle">${e(p.title)}</p><p class="lead">${e(p.description)}</p><p class="tech-line">${p.detailTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="primary-link" href="${e(p.url)}">View repository ↗</a>${back}</div></section>
 <section class="section near-black risk-flow"><div class="container"><p class="eyebrow">ANALYTICAL FLOW</p><h2>From activity<br><span class="muted">to a target cohort.</span></h2><ol class="risk-flow-steps" aria-label="Analytical flow"><li>Transaction records</li><li>Customer indicators</li><li><strong>200</strong><span>most active</span></li><li><strong>40</strong><span>target customers</span></li></ol><p class="lead">The analysis first aggregates transaction activity to the customer level. It then focuses on the 200 users with the highest trading activity before selecting a 40-customer target cohort using interpretable behavioural risk signals.</p></div></section>
 <section id="signals" class="section risk-signals"><div class="container"><p class="eyebrow">BEHAVIOURAL SIGNALS</p><h2>Four signals.<br><span class="muted">Different dimensions of risk.</span></h2><ol class="risk-signal-list">${signals}</ol></div></section>
 <section id="cohort" class="section near-black risk-cohort"><div class="container"><p class="eyebrow">COHORT SELECTION</p><h2>Activity first.<br><span class="muted">Risk signals second.</span></h2><div class="risk-cohort-visual" aria-label="200 most active customers narrowed to 40 target customers"><div><strong>200</strong><span>MOST ACTIVE</span></div><span class="risk-cohort-arrow" aria-hidden="true">→</span><div><strong>40</strong><span>TARGET CUSTOMERS</span></div></div><p class="lead">The analysis first retained the 200 customers with the highest number of trades. Within that group, the final 40 were selected by sorting first on High Exposure Events, then FOMO Count, and then Market Order Ratio.</p><p class="risk-note">Reloading was engineered as a behavioural indicator but was not used as a final cohort-ranking criterion.</p><div class="risk-evidence-intro"><p class="eyebrow">SELECTION VIEW</p><h3>Where the selected cohort sits.</h3></div><figure class="risk-evidence-figure">${renderExposureFomo(figures)}<figcaption>Red outlines indicate the selected cohort. Because High Exposure Events and FOMO Count are part of the ranking criteria, this view visualises where the selected customers sit in the signal space rather than independently validating the selection.</figcaption></figure></div></section>
 <section id="outcomes" class="section risk-outcomes"><div class="container"><p class="eyebrow">OBSERVED OUTCOME</p><h2>Risk signals did not equal losses.</h2><p class="lead">The selected cohort contained both profitable and loss-making outcomes. Net PnL was not used to construct the cohort, so these outcomes reinforce the role of the behavioural signals as a review-prioritisation mechanism rather than a deterministic prediction of customer loss.</p><figure class="risk-evidence-figure">${renderSelectedPnl(figures)}<figcaption>The selected customers span both positive and negative Net PnL outcomes, with wide downside dispersion in the observed sample. The signals therefore identify customers for focused review rather than defining a loss-only segment.</figcaption></figure></div></section>
 <section id="decisions" class="section risk-decisions"><div class="container"><p class="eyebrow">DECISION USE</p><h2>Signals for review.<br><span class="muted">Not automatic judgement.</span></h2><ol class="risk-decision-list">${decisions}</ol><p class="risk-note">These are potential applications of the analysis, not measured intervention outcomes.</p></div></section>
 <section id="scope" class="section near-black risk-scope"><div class="container"><p class="eyebrow">SCOPE</p><h2>Behavioural indicators.<br><span class="muted">Not behavioural diagnoses.</span></h2><p class="lead">${e(p.scope)}</p><a class="case-cta" href="${e(p.url)}">Explore the analysis ↗</a><p class="risk-note">R Markdown source · rendered analysis · reproducible analytical workflow</p></div></section>`;
 return casePage({title:p.title,description:p.description,nav:[['overview','Overview'],['signals','Signals'],['cohort','Cohort'],['outcomes','Outcomes'],['decisions','Decisions']],body,pagination,pageClass:'risk-page'});
}
export function modellingPage(p,pagination){
 const flow=(labels,extra='')=>`<ol class="modelling-flow ${extra}">${labels.map(label=>`<li>${e(label)}</li>`).join('')}</ol>`;
 const body=`<section id="overview" class="case-hero modelling-hero container"><p class="eyebrow">STATISTICAL MODELLING / DECISION UNDER UNCERTAINTY</p><h1 class="reveal ready">Models built<br><span>for uncertainty.</span></h1><noscript><style>.modelling-hero h1.reveal.ready{opacity:1;transform:none}</style></noscript><p class="case-subtitle">${e(p.caseTitle)}</p><p class="lead">${e(p.description)}</p><p class="tech-line">${p.detailTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="primary-link" href="${e(p.url)}">View repository ↗</a>${back}</div></section>
 <section id="robustness" class="section near-black modelling-robustness"><div class="container"><p class="eyebrow">PART 01 / ROBUST ALGORITHM EVALUATION</p><h2>A winner on one problem.<br><span class="muted">Still a winner across many?</span></h2><p class="lead">Five Differential Evolution configurations were first evaluated on a single benchmark problem, then re-evaluated across 26 benchmark problems using a blocked design that accounts for problem difficulty.</p>${flow(['Single benchmark','Configuration comparison','Multi-problem blocked design','Multi-problem recommendation'])}
 <div class="modelling-subsection"><h3>Single-problem pilot.</h3><p>The pilot compares Differential Evolution configurations on one benchmark using log-loss as the performance measure.</p><dl class="modelling-method-list"><div><dt>ONE-WAY ANOVA</dt><dd>Tests whether configuration choice changes mean log-loss.</dd></div><div><dt>TUKEY COMPARISONS</dt><dd>Examines pairwise differences with simultaneous confidence intervals.</dd></div><div><dt>EFFECT SIZE</dt><dd>Uses Cohen’s d to assess whether the difference between the leading configurations is practically meaningful.</dd></div></dl><p class="modelling-note">The pilot identified statistically meaningful differences between configurations.</p></div>
 <div class="modelling-subsection"><h3>Then the problem changed.</h3><p>To test whether the pilot decision generalises, the configurations were evaluated across multiple benchmark problems. Problem difficulty was treated as a blocking factor so that configuration differences could be assessed after controlling for variation between benchmarks.</p>${flow(['Multiple benchmark problems','Problem-level cell means','Blocked ANOVA','Dunnett comparisons'],'modelling-flow-compact')}<p class="modelling-note">Repeated runs within each Method × Problem cell were averaged before the blocked analysis to avoid pseudo-replication. Dunnett comparisons used the pilot winner as the reference.</p></div>
 <div class="modelling-result"><p class="eyebrow">ROBUSTNESS RESULT</p><h3>The recommendation changed.</h3><div class="modelling-model-pair" aria-label="Pilot Config C changed to multi-problem Config B"><div><span>ONE-PROBLEM PILOT</span><strong>Config C</strong></div><span aria-hidden="true">→</span><div><span>26-PROBLEM EVALUATION</span><strong>Config B</strong></div></div><p>Config C had the lowest pilot mean log-loss, but Config B had the lowest mean log-loss across 26 benchmark problems using problem-level cell means.</p><p>This illustrates why a strategy selected under one set of conditions can be unstable when the decision environment changes.</p></div></div></section>
 <section id="pipeline" class="section modelling-pipeline"><div class="container"><p class="eyebrow">PART 02 / PREDICTIVE MODELLING</p><h2>Leakage-aware.<br><span class="muted">From split to deployment simulation.</span></h2><p class="lead">The second study builds a complete classification workflow around grouped observations, correlated predictors, missing values and mild class imbalance.</p>${flow(['Group-aware split','Preprocessing','Elastic Net','Grouped CV','Held-out test','Deployment simulation'],'modelling-flow-six')}
 <div class="modelling-subsection"><h3>Groups stay together.</h3><p>The train/test split is performed by Info_group so that observations from the same group do not leak across training and test sets.</p><p class="modelling-note">The same grouping structure is preserved during cross-validation.</p></div>
 <div class="modelling-subsection"><h3>Preprocessing, inside the workflow.</h3>${flow(['Missing values','Encoding','Yeo–Johnson','Normalisation','PCA','Training-only balancing'],'modelling-flow-six modelling-flow-compact')}<p>Numeric missing values use median imputation; nominal missing values use mode imputation, followed by one-hot encoding. Yeo–Johnson reduces skew and normalisation scales features. PCA retained 137 components to preserve approximately 95% of variance. Downsampling occurs inside the training workflow only.</p></div>
 <div class="modelling-subsection"><h3>Baseline first.<br>Regularisation second.</h3><p>A standard logistic regression provides a baseline. The final model is an Elastic Net logistic regression, chosen for a high-dimensional and correlated feature space.</p><div class="modelling-model-pair"><div><span>BASELINE</span><strong>Logistic regression</strong></div><span aria-hidden="true">→</span><div><span>TUNED MODEL</span><strong>Elastic Net logistic regression</strong></div></div><p class="modelling-note">Penalty and mixture are tuned using grouped cross-validation.</p></div>
 <div class="modelling-subsection"><h3>Tune on training.<br>Evaluate once.</h3><p>Hyperparameters are selected using grouped five-fold cross-validation, with F1 used as the primary tuning metric. The final model is then evaluated once on the held-out test set, where F1 was 0.604.</p><p class="modelling-note">Accuracy, precision, recall and F1 are reported together because the intended operating point depends on the cost of false positives and false negatives.</p></div>
 <div class="modelling-subsection"><h3>From evaluation to unseen data.</h3><p>The final workflow is applied to an unlabeled holdout dataset to simulate a deployment-style prediction step.</p></div></div></section>
 <section id="evidence" class="section near-black modelling-evidence"><div class="container"><p class="eyebrow">EVIDENCE</p><h2>Different problems.<br><span class="muted">Different safeguards.</span></h2><div class="modelling-evidence-grid"><div><p class="eyebrow">ROBUST EVALUATION</p><p>5 configurations → 26 benchmark problems → problem-level cell means → blocked ANOVA</p><strong>Pilot Config C → multi-problem Config B.</strong></div><div><p class="eyebrow">PREDICTIVE PIPELINE</p><p>Group-aware split → preprocessing → Elastic Net → grouped five-fold CV → held-out test → deployment simulation</p><strong>137 retained PCA components · 0.604 held-out F1.</strong></div></div></div></section>
 <section id="scope" class="section modelling-scope"><div class="container"><p class="eyebrow">SCOPE</p><h2>Strong methodology.<br><span class="muted">Simulated settings.</span></h2><p class="lead">The optimisation study uses simulated benchmark problems, so robustness across those benchmarks should not be interpreted as production-market robustness. The classification result belongs to this dataset and held-out split; its operating point and practical value would still depend on the real deployment context. The unseen holdout prediction is a deployment simulation.</p><p class="modelling-note">Assumption checks remain diagnostics rather than proofs, and broader benchmark sets or non-parametric robustness checks would strengthen future analysis.</p><p class="tech-line">${p.methodsTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="primary-link" href="${e(p.url)}">Explore the repository ↗</a>${back}</div><p class="modelling-note">R Markdown · reproducible statistical analysis · modelling workflow</p></div></section>`;
 return casePage({title:p.caseTitle,description:p.description,nav:[['overview','Overview'],['robustness','Robustness'],['pipeline','Pipeline'],['evidence','Evidence'],['scope','Scope']],body,pagination,pageClass:'modelling-page'});
}
export function dissertationPage(r,story,pagination){
 const body=`<section id="overview" class="case-hero dissertation-hero container"><p class="eyebrow">MSc DISSERTATION / FINANCIAL MARKET DATA</p><h1 class="reveal ready">When liquidity disappears,<br><span>how fast does it come back?</span></h1><noscript><style>.dissertation-hero h1.reveal.ready{opacity:1;transform:none}</style></noscript><p class="lead">A high-frequency market microstructure study examining how quoted spread and displayed L1–5 depth recover after short-term liquidity shocks.</p><p class="project-title-small">${e(r.title)}</p></section>${story}`;
 return casePage({title:r.title,description:r.summary,nav:[['overview','Overview'],['data','Data scale'],['results','Results'],['validation','Validation']],body,pagination,pageClass:'dissertation-page'});
}
