const programme = 'https://www.bristol.ac.uk/study/postgraduate/taught/msc-financial-technology-with-data-science/';

const units = [
  {title:'Statistical Computing and Empirical Methods for Financial Technology', period:'Teaching Block 1', note:'Selected foundation route · SCEM', description:'Statistical computing and empirical methods for analysing financial data, with attention to statistical modelling, evaluation and validation in R.'},
  {title:'Large-Scale Data Engineering for Financial Technology', period:'Teaching Block 1', description:'Engineering data workflows for financial technology at scale, from storage and processing to operational performance.', evidence:'Built and load-tested a queue-driven AWS processing workflow using EC2, S3, SQS and DynamoDB, with CloudWatch-driven Auto Scaling and IAM access control.', metrics:[['~120 files','load-test burst'],['1 → 3 workers','automatic scale-out'],['9 → 6 min','t2.micro vs t3.micro in coursework test conditions']]},
  {title:'Introduction to Financial Technology', period:'Teaching Block 1', description:'Introduced the design and assessment of financial technology applications and the systems that support data-driven finance.', coursework:{title:'Computational market experiments in the Bristol Stock Exchange.', description:'Used the Bristol Stock Exchange (BSE) simulator to search MMM01 market-maker settings across synthetic and real-price-derived environments, then selected a cross-market baseline. Modified MMM02 so recent trade-price variation relative to a moving average adjusted its bidding and markup, and compared the strategies in matched IBM-offset simulations.', metrics:[['5 markets','synthetic, IBM, Copper, Nasdaq and T-Note'],['20 IID runs','per parameter configuration'],['80 matched pairs','MMM01* versus modified MMM02']], result:'In the IBM-offset comparison, mean final balance was 557.95 for MMM01* and 601.39 for modified MMM02 (one-sided paired t-test, p = 0.0017).'}},
  {title:'Advanced Financial Technology', period:'Teaching Block 2', description:'Extended the programme’s financial technology foundations through more advanced applications and their technical assessment.'},
  {title:'Introduction to AI and Data Analytics', period:'Teaching Block 2', description:'Developed analytical training in data analysis, statistical methods and AI-enabled approaches to interpreting data.'},
  {title:'Financial Technology Group Project', period:'Teaching Block 2', description:'Applied the programme’s ideas in a collaborative financial technology implementation project.', project:['MindPass FinTech Escrow DApp','./mindpass.html'], evidence:'Four-person group MVP. Led technical implementation, integration and Sepolia validation; work covered relational data, funding logic, programmable escrow and settlement integration.'},
  {title:'Financial Technology Individual Project', period:'Individual project · academic year', credits:60, description:'A substantial independent research project bringing together programme methods through planning, analysis, documentation and presentation.', project:['High-Frequency Liquidity Shock Detection and Order-Book Resiliency','./liquidity-shock.html'], metrics:[['10','Nasdaq securities'],['37','sessions per security'],['8.66M','one-second market states'],['34.6K','liquidity-shock records'],['3.73M','recovery observations']]}
];

function metrics(items){return `<dl class="bristol-metrics">${items.map(([value,label])=>`<div><dd>${value}</dd><dt>${label}</dt></div>`).join('')}</dl>`}
function unit(unit,index){return `<article class="bristol-unit"><span class="bristol-number">${String(index+1).padStart(2,'0')}</span><div class="bristol-unit-main"><h4>${unit.title}</h4>${unit.note?`<p class="bristol-unit-note">${unit.note}</p>`:''}<p>${unit.description}</p>${unit.evidence?`<p class="bristol-evidence">${unit.evidence}</p>`:''}${unit.coursework?`<div class="bristol-coursework"><p class="bristol-coursework-label">SELECTED COURSEWORK EVIDENCE</p><h5>${unit.coursework.title}</h5><p>${unit.coursework.description}</p>${metrics(unit.coursework.metrics)}<p class="bristol-coursework-result">${unit.coursework.result}</p></div>`:''}${unit.metrics?metrics(unit.metrics):''}${unit.project?`<div class="bristol-project"><p>RELATED PORTFOLIO EVIDENCE</p>
<strong>${unit.project[0]}</strong><a href="${unit.project[1]}" aria-label="View project: ${unit.project[0]}"><em>View project →</em></a></div>`:''}</div><div class="bristol-unit-meta"><p>${unit.credits||20} credits</p>
<p>${unit.period}</p></div></article>`}

export function bristolPage(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#000000"><title>Mingyu Wang | University of Bristol</title><meta name="description" content="Mingyu Wang's MSc Financial Technology with Data Science at the University of Bristol, covering financial technology, statistical computing, data analytics, cloud data engineering and applied research."><link rel="icon" href="./assets/favicon.svg"><link rel="stylesheet" href="./assets/styles.css"><script src="./assets/app.js" defer></script></head><body id="top" class="bristol-page"><a class="skip-link" href="#main">Skip to content</a><header class="glass-nav"><a class="wordmark" href="./index.html">Mingyu Wang<span class="brand-dot" aria-hidden="true">.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links">Menu <span aria-hidden="true">+</span></button><nav id="nav-links" aria-label="Education page navigation"><a href="#programme">Programme</a><a href="#curriculum">Curriculum</a><a href="#outcomes">Outcomes</a><a href="#status">Status</a></nav></header><main id="main" tabindex="-1">
<section class="bristol-hero"><div class="container"><p class="eyebrow">MINGYU WANG / EDUCATION</p><div class="bristol-hero-type reveal ready"><h1>University of Bristol</h1>
<p class="bristol-degree">MSc Financial Technology<br>
with Data Science</p></div><noscript><style>.bristol-hero-type.reveal.ready{opacity:1;transform:none}</style></noscript><div class="bristol-hero-meta"><p>2025–2026</p>
<p>School of Engineering Mathematics and Technology</p></div><p class="bristol-hero-status">Dissertation completed · Final results expected November 2026</p><div class="bristol-hero-actions"><a href="./index.html#education">Back to portfolio <span aria-hidden="true">←</span></a><a href="${programme}" target="_blank" rel="noopener noreferrer" aria-label="Official University of Bristol MSc programme, opens in a new tab">Official programme <span aria-hidden="true">↗</span></a></div><p class="bristol-rankings">TIME 2026 #35 <span aria-hidden="true">·</span> QS 2027 #57 <span aria-hidden="true">·</span> THE 2026 =#80</p></div></section>
<section class="bristol-section bristol-intro near-black" id="programme"><div class="container"><p class="eyebrow">THE PROGRAMME</p><h2>Technology, data<br>and finance.</h2><p class="lead">An engineering-led MSc connecting financial technology with computational and statistical methods, data analytics, large-scale data engineering and applied project work.</p><dl class="bristol-glance"><div><dd>1 year</dd><dt>full-time</dt></div><div><dd>180</dd><dt>MSc credits</dt></div><div><dd>7 units</dd><dt>including project work</dt></div><div><dd>60</dd><dt>individual-project credits</dt></div></dl></div></section>
<section class="bristol-section" id="curriculum"><div class="container"><p class="eyebrow">THE ACTUAL ROUTE / 2025–2026</p><h2>My curriculum.</h2><p class="bristol-section-note">SCEM was my selected foundation unit. The curriculum below reflects my 2025–2026 study route.</p><div class="bristol-block"><h3>Teaching Block 1 <span>60 credits</span></h3>${units.slice(0,3).map((u,i)=>unit(u,i)).join('')}</div><div class="bristol-block"><h3>Teaching Block 2 <span>60 credits</span></h3>${units.slice(3,6).map((u,i)=>unit(u,i+3)).join('')}</div><div class="bristol-block bristol-project-block"><h3>Individual project <span>60 credits</span></h3>${unit(units[6],6)}</div><div class="bristol-total"><p>Programme total</p>
<p><strong>180 credits</strong></p></div><p class="bristol-source">The <a href="${programme}" target="_blank" rel="noopener noreferrer" aria-label="University of Bristol MSc programme, opens in a new tab">official programme page ↗</a> explains the foundation choice and compulsory units. Module descriptions here are concise summaries based on the published programme structure.</p></div></section>
<section class="bristol-section near-black" id="outcomes"><div class="container"><p class="eyebrow">THE SYNTHESIS</p><h2>What the degree<br>brought together.</h2><div class="bristol-themes"><div><h3>Data &amp; statistics</h3><p>R · statistical modelling · empirical analysis · validation</p></div><div><h3>Financial technology</h3><p>FinTech systems · market data · risk analytics · programmable finance</p></div><div><h3>Cloud &amp; data systems</h3><p>AWS · data pipelines · relational data · scalable processing</p></div><div><h3>Applied research</h3><p>Research design · reproducibility · independent analysis · technical communication</p></div></div></div></section>
<section class="bristol-section" id="status"><div class="container"><p class="eyebrow">CURRENT RECORD</p><h2>Programme status.</h2><dl class="bristol-status"><div><dt>Programme</dt><dd>MSc Financial Technology with Data Science</dd></div><div><dt>Study period</dt><dd>2025–2026</dd></div><div><dt>Taught modules</dt><dd>Completed</dd></div><div><dt>Individual project</dt><dd>Completed</dd></div><div><dt>Viva</dt><dd>Completed</dd></div><div><dt>Final results</dt><dd>Expected November 2026</dd></div></dl><a class="bristol-return" href="./index.html#education">Back to portfolio ←</a></div></section></main><footer class="container"><p>Mingyu Wang</p>
<p>Data. Evidence. Understanding.</p>
<a href="#top">Back to top ↑</a></footer></body></html>`}
