import {escapeHTML as e} from './utils.mjs';
export function projectPreviews(c, locale='en'){
 const zh=locale==='zh-TW';
 const caseHref=href=>zh?href.replace(/^\.\//,'../'):href;
 const r=c.research;
 const flagship=`<article id="dissertation" class="project-preview flagship"><p class="eyebrow">${zh?'01 / 碩士論文 / 金融市場資料':'01 / MSc Dissertation / Financial Market Data'}</p><div class="preview-title"><h3>${e(r.title)}</h3><p>${e(r.summary)}</p></div><dl class="preview-facts"><div><dt>${zh?'標準化的一秒市場狀態':'standardised one-second market states'}</dt><dd>${(r.scale.marketStates/1e6).toFixed(2)}M</dd></div><div><dt>${zh?'依類別區分的流動性衝擊紀錄':'family-specific liquidity-shock records'}</dt><dd>${(r.scale.shockRecords/1e3).toFixed(1)}K</dd></div><div><dt>${zh?'事件－秒層級復原觀測':'event-second recovery observations'}</dt><dd>${(r.scale.recoveryRows/1e6).toFixed(2)}M</dd></div></dl><div class="preview-recovery"><div><span>${zh?'價差':'Spread'}</span><strong>${r.spreadMedian}<small> s</small></strong></div><div><span>${zh?'深度':'Depth'}</span><strong>${r.depthMedian}<small> s</small></strong></div><p>${zh?'已達 T90 事件的合併<br>首次通過時間中位數':'Pooled reached-only <br>median first-passage T90'}</p></div><p class="tech-line">${r.technologies.map(e).join(' · ')}</p><a class="case-cta" href="${e(caseHref(r.caseStudy))}" aria-label="${zh?'查看案例':'View case study'}: ${e(r.title)}">${zh?'查看案例':'View case study'} <span aria-hidden="true">→</span></a></article>`;
 return flagship+c.projects.map((p,i)=>{
  const facts=p.previewEvidence.map(([value,label])=>`<div><dt>${e(label)}</dt><dd>${e(value)}</dd></div>`).join('');
  return `<article id="${e(p.id)}" class="project-preview work-preview"><p class="eyebrow">${String(i+2).padStart(2,'0')} / ${e(p.category)}</p><div class="preview-title"><h3>${e(p.title)}</h3><div><p>${e(p.summary||p.description)}</p>${p.previewContribution?`<p class="preview-context">${e(p.previewContribution)}</p>`:''}</div></div><dl class="preview-facts ${p.previewEvidence.length===2?'preview-facts--two':''}">${facts}</dl><div class="preview-recovery work-preview-secondary"><div><strong>${e(p.previewInsight)}</strong></div><p>${e(p.previewInsightNote)}</p></div><p class="tech-line">${p.previewTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="case-cta" href="${e(caseHref(p.caseStudy))}" aria-label="${zh?'查看案例':'View case study'}: ${e(p.title)}">${zh?'查看案例':'View case study'} <span aria-hidden="true">→</span></a><a href="${e(p.url)}" aria-label="${zh?'查看 GitHub 儲存庫':'View GitHub repository'}: ${e(p.title)}">GitHub ↗</a>${p.prototypeUrl?`<a href="${e(p.prototypeUrl)}" aria-label="${zh?'查看線上原型':'View live prototype'}: ${e(p.title)}">Live ↗</a>`:''}</div></article>`;
 }).join('');
}
