import {escapeHTML as e} from './utils.mjs';
export function projectPreviews(c){
 const r=c.research;
 const flagship=`<article id="dissertation" class="project-preview flagship"><p class="eyebrow">01 / MSc Dissertation / Financial Market Data</p><div class="preview-title"><h3>${e(r.title)}</h3><p>${e(r.summary)}</p></div><dl class="preview-facts"><div><dt>standardised one-second market states</dt><dd>${(r.scale.marketStates/1e6).toFixed(2)}M</dd></div><div><dt>family-specific liquidity-shock records</dt><dd>${(r.scale.shockRecords/1e3).toFixed(1)}K</dd></div><div><dt>event-second recovery observations</dt><dd>${(r.scale.recoveryRows/1e6).toFixed(2)}M</dd></div></dl><div class="preview-recovery"><div><span>Spread</span><strong>${r.spreadMedian}<small> s</small></strong></div><div><span>Depth</span><strong>${r.depthMedian}<small> s</small></strong></div><p>Pooled reached-only <br>median first-passage T90</p></div><p class="tech-line">${r.technologies.map(e).join(' · ')}</p><a class="case-cta" href="${e(r.caseStudy)}">View case study <span aria-hidden="true">→</span><span class="sr-only">: ${e(r.title)}</span></a></article>`;
 return flagship+c.projects.map((p,i)=>{
  const facts=p.previewEvidence.map(([value,label])=>`<div><dt>${e(label)}</dt><dd>${e(value)}</dd></div>`).join('');
  return `<article id="${e(p.id)}" class="project-preview work-preview"><p class="eyebrow">${String(i+2).padStart(2,'0')} / ${e(p.category)}</p><div class="preview-title"><h3>${e(p.title)}</h3><div><p>${e(p.summary||p.description)}</p>${p.previewContribution?`<p class="preview-context">${e(p.previewContribution)}</p>`:''}</div></div><dl class="preview-facts ${p.previewEvidence.length===2?'preview-facts--two':''}">${facts}</dl><div class="preview-recovery work-preview-secondary"><div><strong>${e(p.previewInsight)}</strong></div><p>${e(p.previewInsightNote)}</p></div><p class="tech-line">${p.previewTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="case-cta" href="${e(p.caseStudy)}">View case study <span aria-hidden="true">→</span><span class="sr-only">: ${e(p.title)}</span></a><a href="${e(p.url)}">GitHub ↗</a>${p.prototypeUrl?`<a href="${e(p.prototypeUrl)}">Live ↗</a>`:''}</div></article>`;
 }).join('');
}
