import {escapeHTML as e} from './utils.mjs';
import {casePage} from './case-layout.mjs';
export {escapeHTML} from './utils.mjs';

export function renderCaseStudy(p,pagination){
 const lifecycle=p.lifecycleLabels.map(label=>`<li>${e(label)}</li>`).join('');
 const capabilities=p.capabilities.map(([title,copy],i)=>`<li><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${e(title)}</h3><p>${e(copy)}</p></li>`).join('');
 const architecture=p.architectureLayers.map(layer=>`<li>${e(layer)}</li>`).join('');
 const contributions=p.contributions.map(([title,copy],i)=>`<li><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${e(title)}</h3><p>${e(copy)}</p></li>`).join('');
 const validation=p.validationLayers.map(([title,copy])=>`<div><h3>${e(title)}</h3><p>${e(copy)}</p></div>`).join('');
 const body=`<section id="overview" class="case-hero mindpass-hero container"><p class="eyebrow">FINTECH / UNIVERSITY GROUP MVP</p><h1 class="reveal ready">Programmable settlement<br><span>for appointment-based services.</span></h1><noscript><style>.mindpass-hero h1.reveal.ready{opacity:1;transform:none}</style></noscript><p class="case-subtitle">${e(p.title)}</p><p class="lead">${e(p.description)}</p><p class="project-context">${e(p.period)} · ${e(p.context)}</p><p class="tech-line">${p.heroTechnologies.map(e).join(' · ')}</p><div class="actions project-actions"><a class="primary-link" href="${e(p.prototypeUrl)}">View live prototype ↗</a><a href="${e(p.url)}">GitHub ↗</a><a href="./index.html#work">← All Work</a></div></section>
 <section id="product" class="section mindpass-product near-black"><div class="container"><p class="eyebrow">PRODUCT</p><h2>More than<br><span class="muted">a payment button.</span></h2><div class="mindpass-product-copy">${p.productParagraphs.map(copy=>`<p>${e(copy)}</p>`).join('')}</div><ol class="mindpass-lifecycle" aria-label="Request to withdrawal lifecycle">${lifecycle}</ol></div></section>
 <section id="features" class="section mindpass-features container"><p class="eyebrow">FEATURES</p><h2>One lifecycle.<br><span class="muted">Multiple outcomes.</span></h2><ol class="mindpass-feature-grid">${capabilities}</ol></section>
 <section id="architecture" class="section mindpass-architecture near-black"><div class="container"><p class="eyebrow">ARCHITECTURE</p><h2>Settlement on-chain.<br><span class="muted">Coordination off-chain.</span></h2><p class="lead">${e(p.architectureSummary)}</p><ol class="mindpass-architecture-flow" aria-label="Wallet to off-chain mirror">${architecture}</ol><p class="mindpass-supporting">${e(p.architectureNote)}</p><p class="tech-line">${p.architectureTechnologies.map(e).join(' · ')}</p></div></section>
 <section id="contribution" class="section mindpass-contribution container"><p class="eyebrow">MY CONTRIBUTION</p><h2>I led the build.</h2><p class="lead">${e(p.contributionIntro)}</p><ol class="mindpass-contribution-grid">${contributions}</ol><p class="mindpass-small-note">${e(p.contributionDisclaimer)}</p></section>
 <section id="validation" class="section mindpass-validation near-black"><div class="container"><p class="eyebrow">VALIDATION</p><h2>Tested across<br><span class="muted">the full stack.</span></h2><div class="mindpass-validation-grid">${validation}</div><p class="mindpass-supporting">${e(p.validationScenarios)}</p></div></section>
 <section id="scope" class="section mindpass-scope container"><p class="eyebrow">SCOPE</p><h2>A working MVP.<br><span class="muted">Not a production platform.</span></h2><p class="lead">${e(p.scope)}</p><div class="actions project-actions"><a class="primary-link" href="${e(p.prototypeUrl)}">View live prototype ↗</a><a href="${e(p.url)}">Explore the source ↗</a></div></section>`;
 return casePage({title:p.title,description:p.description,nav:[['overview','Overview'],['product','Product'],['architecture','Architecture'],['contribution','Contribution'],['validation','Validation']],body,pagination,pageClass:'mindpass-page'});
}
